@startuml
'https://plantuml.com/class-diagram

class Point{
    int x;
    int y;
    + String toString();
    + double distances();
}

class Point3D{
    int x;
    int y;
    + String toString();
    + double distances();
}

Point <|-- Point3D

@enduml