@startuml
'https://plantuml.com/class-diagram

class Person{
    String name;
    String gender;
    int age;
    + String toString();
}

class Student {
    String school;
}

class Employee{
    double salary
}

'继承、扩展、泛化
Person <|-- Student
Person <|-- Employee

@enduml