@startuml
'https://plantuml.com/class-diagram

class Weapon{
    String name;
    int bullets;
    void fire();
    void reload();
}

class Soldier{
    int id;
    int blood;
    Weapon weapon;-->空引用
    'null
}

Soldier o-- Weapon

@enduml