@startuml
'https://plantuml.com/class-diagram

class Point{
    int x;
    int y;
    void fuZhi();
    void point();
}

class Test{
 {static} void main(String[] args);
}

'普通的调用关系
Test --> Point
'组合关系
Circle  *-- Point

interface a{}
@enduml